# Generated by Django 4.2.5 on 2023-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-05-23'),
            preserve_default=False,
        ),
    ]
